//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMuaHang
    {
        public int IdCTMH { get; set; }
        public Nullable<int> IdMuaHang { get; set; }
        public Nullable<int> IdSach { get; set; }
        public Nullable<decimal> UnitGiaSale { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual MuaHang MuaHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
