//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MuaHang()
        {
            this.ChiTietMuaHangs = new HashSet<ChiTietMuaHang>();
        }
    
        public int IdMuaHang { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string SDT_KH { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuaHang> ChiTietMuaHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual User User { get; set; }
    }
}
