//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.MuaHangs = new HashSet<MuaHang>();
        }
    
        public int IdUser { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên đầu!")]
        public string TenDau { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên cuối!")]
        public string TenCuoi { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập email!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập password!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Vui lòng xác nhận password!")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        public string LogInErrorMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuaHang> MuaHangs { get; set; }
    }
}
